Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define :master do |master|
    master.vm.hostname = "10.211.55.110"
    master.vm.provider :virtualbox do |v|
      v.name = "10.211.55.110"
      v.memory = 1024
      v.cpus = 2
    end
    master.vm.network :private_network, ip: "10.211.55.110"
    master.vm.provision :shell, path: "bootstrap_master.sh"
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end


